### ISSUE TITLE
Week 1 - Section "Judges"

### ISSUE THREAD

**Issue by George9897** [UT-Applicataion-Development-Association/Innovation-Fair#3]
- Judge introduction

**Comment by Altair59** [comment]
working on judge

**Comment by evelyh** [comment]
<raise hand>

**Comment by Altair59** [comment]
Altair59 and evelyh had completed judge section and PM says it's ok.

**Comment by Falanke21** [comment]
Css names needs to be changed. Please ask Eve for detail ;)
