### ISSUE TITLE
Language setting in timeline

### ISSUE THREAD

**Issue by Falanke21** [UT-Applicataion-Development-Association/Innovation-Fair#34]
![image](https://user-images.githubusercontent.com/39153483/85763174-729d5880-b6e2-11ea-88e4-f5866f83e445.png)

Add switch language feature in timeline

**Comment by rainyuxuan** [comment]
solved; 
![image](https://user-images.githubusercontent.com/42298884/85956715-a9c77000-b955-11ea-9cb8-b7b538b02993.png)
