### ISSUE TITLE
两位评委和讲师的信息需要更新

### ISSUE THREAD

**Issue by zileepy** [UT-Applicataion-Development-Association/Innovation-Fair#44]
两位评委和讲师的信息需要更新，如下：

Speakers：
Jamie Waese, UX Architect - IBM

Judges:
Jamie Waese, UX Architect - IBM
Abdullah Monoar, Senior Fullstack Developer - Q4

**Comment by Altair59** [comment]
issue fixed: two jdgs/spkers info updated.
issue can be closed now.

**Comment by kwanstyle** [comment]
I saw your commit: https://github.com/UT-Applicataion-Development-Association/Innovation-Fair/commit/94e5f246876b36af0baf38b3e4aa98ae1841180e

**Comment by zileepy** [comment]
Verified in the latest master branch and the deployed page. Closing this issue.
